### ISSUE TITLE
The PyPI source tarball for 1.28 doesn't contain requirements.txt

### ISSUE THREAD

**Issue by WOnder93** [arighi/virtme-ng#156]
After the fix for #146 it is now not possible to build the package from PyPI source tarball, because it doesn't include the `requirements.txt` file:
```
Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 568, in main
    generate_requires(
    ~~~~~~~~~~~~~~~~~^
        include_runtime=args.runtime,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        config_settings=parse_config_settings_args(args.config_settings),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 464, in generate_requires
    generate_build_requirements(backend, requirements)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 282, in generate_build_requirements
    new_reqs = get_requires(config_settings=requirements.config_settings)
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 176, in <module>
  File "<string>", line 44, in parse_requirements
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by arighi** [comment]
Thanks for reporting this, it should be fixed by #157, I'll cut a new version.

**Comment by arighi** [comment]
Merged, pushed a new version and tested: https://pypi.org/project/virtme-ng/1.29/

**Comment by WOnder93** [comment]
Thanks! It indeed works now :+1:
